shiki-natsume:
  messages:
    attack:
      - "……啊?"
      - "啊?"
      - "……啧……"
    kill:
      - "你叫唤什么?"
      - "烦死了，给我闭嘴"
      - "你脑子有病吗"
      - "啊? 你脑子有病吗?"
    hold:
      - "喂?"
      - "喂"
    damage:
      - "诋毁?"
      - "闷骚， 烦人"
      - "真的好恶心"
      - "……嗯……"
    break:
      - "……哈?"
      - "…………"